### ISSUE TITLE
Fails to build with qt5-5.11.0beta1 on archlinux

### ISSUE THREAD

**Issue by mmetak** [cmdrkotori/mpc-qt#171]
```
g++ -c -pipe -Wall -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o manager.o manager.cpp
mainwindow.cpp: In member function ‘QPoint MainWindow::desirablePosition(QSize&, bool)’:
mainwindow.cpp:262:20: error: incomplete type ‘QStyle’ used in nested name specifier
     return QStyle::alignedRect(Qt::LeftToRight, Qt::AlignCenter,
                    ^~~~~~~~~~~
make: *** [Makefile:1203: mainwindow.o] Error 1
make: *** Waiting for unfinished jobs....
```

After adding `#include <QStyle>` to `mainwindow.cpp`it builds fine.

Builds just fine with `qt5-5.10.1` though.

**Comment by ahjolinna** [comment]
good to know but its still way too early for Qt5.11, as it will have frequent beta releases [(1-2 weeks intervals)](https://blog.qt.io/blog/2018/03/01/qt-5-11-beta-released/) so there could be still many thing happening for it before it's stable enough...when RC version is out then I think 5.11 support should be looked at
